### ISSUE TITLE
Docs requirements for this project

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kube-scheduler-wasm-extension#14]
**What would you like to be added**:

My ideal document should include:

- What the project structure looks like, e.g. what're the core folders for because this project looks quite different with standard kubernetes projects
- How to write my own scheduler plugin
- How to run the custom kube-scheduler with wasm extension
- How to keep up with the upstream kubernetes because we may have to update the proto files regularly
- ...

If possible, we can also have some tutorials for wasm beginners for most of them come from the kubernetes world, I guess so.
This is a long term plans, hope to finish them before the first release.

/kind documentation
/kind help
/priority long-term

**Why is this needed**:

For the long term healthy growing of the community.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by sanposhiho** [comment]
Basically agree with @kerthcet. This issue is kinda too big, so let me break it down to smaller issues:

```[tasklist]
### Tasks
- [ ] [Document/contributor guide] The basic folder architecture
- [ ] [Document/user guide] How to write my own scheduler plugin
- [ ] [Document/user guide] How to run the custom kube-scheduler with wasm extension
- [ ] [Document/user guide] How to maintain your wasm plugins
```

**Comment by sanposhiho** [comment]
Close this issue as I created smaller issues, thanks.

/close
